version: "3"
services:
  social_media:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000

    volumes:
      - ./:/usr/src/app:ro

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=social_media
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09rrw2973sd974fs92973fh87b232hdw34iy74827uy2gwduyg3y2
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=600

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=social_media

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
