"""vote user post

Revision ID: 5734eb558e5f
Revises: 
Create Date: 2022-07-26 01:38:57.442048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5734eb558e5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
